select distinct sm.MAJOR_NAME from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.COLLEGE_ABBR = 'ENV DSGN';

select * from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.MAJOR_NAME = 'ARCHITECTURE' and sm.COLLEGE_ABBR != 'ENV DSGN';

select * from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.MAJOR_NAME in 
    ('DESIGN','INDIVIDUAL','URBAN STUDIES','LANDSCAPE ARCH','URBAN DESIGN','CITY REGIONAL PLAN','ARCHITECTURE','LAND ARCH & ENV PLAN') 
and sm.COLLEGE_ABBR != 'ENV DSGN';

select * from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.COLLEGE_ABBR = 'ENV DSGN';

select count(*) from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.COLLEGE_ABBR = 'ENV DSGN'; -- 806

select unique count(*) from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.COLLEGE_ABBR = 'ENV DSGN' or sm.COLLEGE_ABBR2 = 'ENV DSGN' or sm.COLLEGE_ABBR3 = 'ENV DSGN' or sm.COLLEGE_ABBR4 = 'ENV DSGN';  

select * from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.COLLEGE_ABBR = 'ENV DSGN' or sm.COLLEGE_ABBR2 = 'ENV DSGN' or sm.COLLEGE_ABBR3 = 'ENV DSGN' or sm.COLLEGE_ABBR4 = 'ENV DSGN';  

select * from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm


select sm.LDAP_UID from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm
where sm.COLLEGE_ABBR = 'ENV DSGN';

select * from BSPACE_STUDENT_INFO_VW si
where si.STUDENT_LDAP_UID in 
    (select sm.LDAP_UID from BSPACE_STUDENT_MAJOR_VW sm where sm.COLLEGE_ABBR = 'ENV DSGN');  -- 806 rows


select * from BSPACE_STUDENT_INFO_VW si
left join BSPACE_STUDENT_MAJOR_VW sm on si.STUDENT_LDAP_UID = sM.LDAP_UID
where sm.COLLEGE_ABBR = 'ENV DSGN' or sm.COLLEGE_ABBR2 = 'ENV DSGN' or sm.COLLEGE_ABBR3 = 'ENV DSGN' or sm.COLLEGE_ABBR4 = 'ENV DSGN';

select * from BSPACE_STUDENT_INFO_VW si where si.STUDENT_LDAP_UID in 
                 (select sm.LDAP_UID from BSPACE_STUDENT_MAJOR_VW sm where sm.COLLEGE_ABBR = 'ENV DSGN' or sm.COLLEGE_ABBR2 = 'ENV DSGN' 
                 or sm.COLLEGE_ABBR3 = 'ENV DSGN' or sm.COLLEGE_ABBR4 = 'ENV DSGN');


select * from SAKAI_JOHNK.BSPACE_STUDENT_INFO_VW si
where si.STUDENT_LDAP_UID in 
    (select sm.LDAP_UID from SAKAI_JOHNK.BSPACE_STUDENT_MAJOR_VW sm where sm.COLLEGE_ABBR = 'ENV DSGN')
and si.AFFILIATIONS like '%STUDENT-TYPE-REGISTERED%';  -- 806 ROWS

select unique sm.MAJOR_NAME from BSPACE_STUDENT_MAJOR_VW sm
where sm.COLLEGE_ABBR = 'ENV DSGN';


-- 'DESIGN','INDIVIDUAL','URBAN STUDIES','LANDSCAPE ARCH','URBAN DESIGN','CITY REGIONAL PLAN','ARCHITECTURE','LAND ARCH & ENV PLAN'