package edu.berkeley.myberkeley.caldav;

import net.fortuna.ical4j.model.Calendar;
import org.apache.commons.httpclient.URI;
import org.apache.commons.httpclient.URIException;
import org.junit.Before;
import org.junit.Test;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.text.ParseException;

/**
 * Test used just to populate user vbede's calendar with data. This test doesn't clean up after itself!
 */

public class EventGeneratorTest extends CalDavTests {

    private static final String OWNER = "vbede";

    private static final String SERVER_ROOT = "http://test.media.berkeley.edu:8080";

    private static final String USER_HOME = SERVER_ROOT + "/ucaldav/user/" + OWNER + "/calendar/";

    private static final org.slf4j.Logger LOGGER = LoggerFactory.getLogger(CalDavConnectorTest.class);

    private CalDavConnector adminConnector;

    @Before
    public void setup() throws CalDavException, URIException {
        this.adminConnector = new CalDavConnector("admin", "bedework", new URI(SERVER_ROOT, false), new URI(USER_HOME, false));
    }

    @Test
    public void putCalendar() throws CalDavException {
        try {
            Calendar calendar = buildVevent("Put here by CalDavTests");
            this.adminConnector.putCalendar(calendar, OWNER);
        } catch (IOException ioe) {
            LOGGER.error("Trouble contacting server", ioe);
        }
    }

    @Test
    public void putTodo() throws CalDavException, ParseException, URIException {
        try {
            Calendar calendar = buildVTodo("Generated by CalDavTests");
            this.adminConnector.putCalendar(calendar, OWNER);
        } catch (IOException ioe) {
            LOGGER.error("Trouble contacting server", ioe);
        }
    }

}
